(TeX-add-style-hook "news"
 (lambda ()
    (LaTeX-add-bibitems
     "facebook-hack"
     "cc-theft"
     "account-hacks"
     "palin-email"
     "un-cell-stats"
     "pritchard2000"
     "modine2007"
     "spohn"
     "punkbuster"
     "schramm2007"
     "buzzingup2010"
     "sherman2009"
     "peterwurst2010"
     "schneier2005"
     "vilches2010"
     "miller2009"
     "lax"
     "WoW"
     "StarCraft"
     "Artek72"
     "Ward2005"
     "FowlerWSJ2012"
     "RisherImeprium2012"
     "SpamLaws2011"
     "TwitterRules"
     "facecom"
     "boinc"
     "NYTreputationfraud"
     "etfolding")))

