(TeX-add-style-hook "other"
 (lambda ()
    (LaTeX-add-bibitems
     "wong2000sgc"
     "li2001brs"
     "li2000buk"
     "agn"
     "agnw"
     "bertinisays"
     "travis"
     "kelly"
     "subscribers"
     "pendarakis2001aal"
     "mediaflo"
     "wang1996bad"
     "colwellarch"
     "smith2001psp"
     "sikka2007fpr"
     "wikileaks"
     "dalenius1986finding"
     "oecdglossary"
     "ssngen"
     "brucehatestcpa"
     "rosshatestcpa"
     "baughman2001cheat"
     "boazL15ZK"
     "heinonen1998method"
     "megiddo1982linear"
     "bitcoin"
     "Karame:2011:PYB:1963405.1963451"
     "cloudflare"
     "weka"
     "webworker"
     "jmeter"
     "kittydar"
     "bonneville")))

